#!/bin/sh

# Generate file descriptor for shoppingcart example
# TODO do it in build.rs

OUTPUT_DESC=shoppingcart.desc

protoc --proto_path=./ \
    --proto_path=./frontend/ \
    --include_imports \
    -o $OUTPUT_DESC \
    example/shoppingcart/shoppingcart.proto \
    example/shoppingcart/persistence/domain.proto
