#!/bin/sh

# Generate file descriptor for the shopping cart example
# TODO do it in build.rs
#   In Prost! there is a relatively fresh PR for adding file descriptor support: https://github.com/danburkert/prost/pull/326.
# Meanwhile use protobuf library to generate it in `build.rs`

OUTPUT_DESC=src/shoppingcart.desc

protoc --proto_path=./ \
    --proto_path=./frontend/ \
    --include_imports \
    --descriptor_set_out $OUTPUT_DESC \
    example/shoppingcart/shoppingcart.proto \
    example/shoppingcart/persistence/domain.proto
